const fs = require('fs');
const path = require('path');
const file = path.resolve(__dirname, '..', 'LongShotStitch.html');
const html = fs.readFileSync(file, 'utf8');
const versionArchives = fs.readdirSync(path.resolve(__dirname, '..')).filter(name => /^LongShotStitch_v.*\.html$/.test(name));
if (versionArchives.length) throw new Error(`version archive html files should not remain: ${versionArchives.join(', ')}`);
const required = [
  'LongShotStitch v1.31',
  'rel="icon"',
  '✂',
  'autoStitchEnabled',
  'inferAutoOrientation',
  'autoAllSeams',
  'subtitleRegion',
  'subtitleMove',
  'subtitleEdge',
  'generateSubtitleStitch',
  'drawSubtitleRegion',
  'selectedLayoutItem',
  'selectImageForRegionMode',
  'shouldShowImageList',
  'cutSettings',
  'cutLines',
  'ensureCutLines',
  'resetCutLines',
  'completeCutEditing',
  'mobileToolGroupTap',
  'openMobileTextEditor',
  'exportCurrent',
  'exportFormatSelect',
  'exportFormat',
  'exportQuality',
  'exportQualityAuto',
  'smartExportQuality',
  'applySmartExportQuality',
  'exportQualityPanel',
  'exportPresets',
  'exportEstimate',
  'exportLosslessHint',
  'scheduleExportEstimate',
  'renderExportPreviewCanvas',
  'formatBytes',
  'exportMenu',
  'exportDirectBtn',
  'PROXY_LIMITS',
  'shouldUseProxy',
  'schedulePreviewProxy',
  'processPreviewProxyQueue',
  'createPreviewProxy',
  'drawImageItem',
  'imageSourceForDraw',
  'previewImg',
  'proxyStatus',
  'sourceWidth',
  'sourceHeight',
  'exportMode ? im.img : (im.previewImg || im.img)',
  'mobileFileBtn',
  'mobilePrimaryNav',
  'mobile-primary-mode',
  'mobileStitchActions',
  'mobileCutControls',
  'mobileAnnotationTools',
  'mobileStitchMenu',
  'mobileSection',
  'setMobileSection',
  'openStitchLineMenu',
  'runStitchAction',
  'data-stitch-action="manualStitch"',
  'data-stitch-action="autoStitch"',
  'data-stitch-action="autoSubtitle"',
  'data-stitch-action="manualSubtitle"',
  'mobileAutoBtn',
  'mobileDirectionBtn',
  'mobileUndoBtn',
  'mobileRedoBtn',
  'mobileClearBtn',
  'mobileInfoBtn',
  'mobileInfoMenu',
  'mobileInfoText',
  'renderMobileInfoMenu',
  'state.mobileInfoOpen',
  '.statusbar{display:none',
  'mobile-file-menu',
  'data-mobile-file="openImage"',
  'data-mobile-file="openProject"',
  'data-mobile-file="saveProject"',
  'toggleOrientation',
  'showAbout',
  'LongShotStitch v1.31',
  'desktop-compact-card',
  'compact-row',
  'compact-field',
  'compact-actions',
  '.mobile-primary-nav,.mobile-stitch-menu,.mobile-cut-popover{display:none}',
  'lockMobilePanAxis',
  'mobileSafeInset',
  'return isMobileLayout() ? 28 : 0;',
  'activePointers',
  'pinchState',
  'pointerDistance',
  'pointerMidpoint',
  'beginPinchZoom',
  'updatePinchZoom',
  'mobilePanFactor',
  'mobileCutSubmode',
  'cutCropRatio',
  'customCropRatio',
  'mobileCutPopover',
  'mobileCutPopoverOpen',
  'renderMobileCutPopover',
  'mobile-cut-tool',
  'mobile-cut-popover',
  'mobileSplitControls',
  'mobileCropControls',
  'cropRatioSelect',
  'customRatioInput',
  'applyCropRatio',
  'parseCropRatio',
  'data-mobile-cut-mode="split"',
  'data-mobile-cut-mode="crop"',
  'data-mobile-split="ok"',
  'data-mobile-crop="ok"',
  '裁切',
  '分割',
  '裁剪',
  '自定义',
  'downloadCanvasImage',
  'canvasToSvgBlob',
  'keepSeamAnchor',
  'shouldFreezeViewportForActiveEdit',
  "if(!shouldFreezeViewportForActiveEdit()) clampPanToLayout(layoutCache);",
  'anchorScreen',
  'exportCutImages',
  'exportCroppedImage',
  'state.mobileSection === \'cut\' && state.mobileCutSubmode === \'crop\'',
  'drawCutGuides',
  'downloadCanvasPng',
  'data-mode="subtitle"',
  'data-mode="cut"',
  'openInlineTextEditor(h.index, true)',
  '${base}_${rowLabel}_${colLabel}',
  'drag.type === \'cutLine\'',
  'drag.type === \'seamBefore\'',
  'drag.type === \'seamAfter\'',
  'isLiveTextEdit',
  'Keyboard Backspace/Delete must not remove annotations',
  'Rotate around the same visual frame center used by the blue dashed selection box',
  'textSize:14',
  'fontSize:s.textSize || 14',
  'annotationFrame',
  'annotationRotate',
  'textVertical',
  'syncBadgeSequence',
  'c.clip()'
];
for (const token of required) {
  if (!html.includes(token)) throw new Error(`missing token: ${token}`);
}
for (const token of ["if(state.selected?.type === 'annotation'){ deleteSelectedAnnotation(); return; }", "e.key === '1'", "e.key === '2'", "e.key === '3'", "e.key === '4'", "e.key === '5'", "导出 PNG", "<div class=\"mobile-title\">裁剪</div>", "data-mobile-action=\"vertical\"", "data-mobile-action=\"horizontal\"", "id=\"previewBtn\"", "id=\"mobileMoreBtn\"", "id=\"mobileVerticalBtn\"", "id=\"mobileHorizontalBtn\"", "data-mobile-action=\"paste\"", "mobile-more-menu", "exportCutPanel", "exportCutSize", "exportCutModeSelect", "applyExportCutSettings", "cutExportSizeText", "切割", "mobile-cut-mode-tabs"]) {
  if (html.includes(token)) throw new Error(`forbidden token remains: ${token}`);
}
console.log('static_check ok');
